In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
from numpy import*

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [15]:
np.zeros(5) #Parameter tuning

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5, dtype=int) #Hyperparameter tuning #1d array

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,2)) #2d arrary 

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2,2),dtype=int)    # 2 X 2 matrix or 2 X 2 array

array([[0, 0],
       [0, 0]])

In [20]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
rand(4)

NameError: name 'rand' is not defined

In [24]:
random.rand(4)

array([0.29995476, 0.19598191, 0.47465797, 0.57513583])

In [26]:
np.random.rand(3,2)

array([[0.27603791, 0.82920487],
       [0.55437534, 0.61878375],
       [0.76936274, 0.58568558]])

In [29]:
np.random.randint(4) # Number will shuffle every time

3

In [30]:
np.random.randint(10,15)

11