ARRAY CREATING FUNCTION

In [1]:
import numpy as np

In [2]:
a = np.array([4,5,6])
print("Array a:",a)

Array a: [4 5 6]


In [6]:
b = np.arange(0,15,4)
print("Array b:",b)

Array b: [ 0  4  8 12]


In [7]:
c = np.ones((4,4))
print("Array c:\n",c)

Array c:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
d = np.zeros((3,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
e = np.identity(3)
print("Identical Matrix:",e)

Identical Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ARRAY MANIPULATION 

In [10]:
# FLATTENED ARRAY
f = np.array([[1,2],[3,4],[5,6],[7,8]]) # It coverts all into One array 
flattened = np .ravel(f)
print("Flattened Array :",flattened)

Flattened Array : [1 2 3 4 5 6 7 8]


In [14]:
# TRANSPOSED ARRAY
e = np.array([[1,2,3],[4,5,6],[7,8,9]]) # It converts rows to columns and columns to rows
transposed = np.transpose(e)
print("Transposed Array :\n",transposed)

Transposed Array :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [15]:
# Stack Arrays Vertically 
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Stacked Array:\n",stacked)

Stacked Array:
 [[1 2]
 [3 4]]


In [17]:
# Stack Arrays horizontally 
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print("Stacked Array:\n",stacked)

Stacked Array:
 [1 2 3 4]


MATHEMATICAL FUNCTION 

In [2]:
f = np.array([1,2,3,4,5])
add = np.add(f,2)
print("Addition :",add)

Addition : [3 4 5 6 7]


In [23]:
g = np.array([4,5,6,7])
sub = g-3
print("Subtraction :",sub)

Subtraction : [1 2 3 4]


In [24]:
h = np.array([5,6,4])
mul = h*5
print("Multiplication :",mul)

Multiplication : [25 30 20]


In [25]:
i = np.array([2,6,4])
div = i/2
print("Divison :",div)

Divison : [1. 3. 2.]


In [26]:
i = np.array([2,6,4])
div = i//2
print(" Floor Divison :",div)

Divison : [1 3 2]


In [27]:
i = np.array([2,6,4])
rem = i%2
print("Remainder :",rem)

Remainder : [0 0 0]


In [29]:
i = np.array([2,6,4])
power = i**3
print("Power :",power)

Power : [  8 216  64]


In [32]:
print(g)
print(h)
print(f)
print(i)

[4 5 6 7]
[5 6 4]
[1 2 3 4 5]
[2 6 4]


In [33]:
# DOT PRODUCT
dot_product = np.dot(h,i)
print("Dot product :",dot_product)

Dot product : 62


In [34]:
#DOT PRODUCT
# IF SIZE ARRAYS IS DIFFERENT IT WON'T WORK 
dot_product = np.dot(f,g)
print("Dot product of f and g:",dot_product)

ValueError: shapes (5,) and (4,) not aligned: 5 (dim 0) != 4 (dim 0)

STATISTICAL FUNCTIONS

In [35]:
min = np.min(i)
print("Min Value:",min)

Min Value: 2


In [36]:
max = np.max(i)
print("Max Value:",max)

Max Value: 6


In [38]:
Mean=np.mean(f)
print("Mean :",Mean)

Mean : 3.0


In [40]:
Standard_deviation=np.std(f)
print("Standard deviation : ",Standard_deviation)

Standard deviation :  1.4142135623730951


In [3]:
Median=np.median(f)
print("Median :",Median)

Median : 3.0


RANDOM SAMPLING FUNCTIONS

In [41]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("random_values :",random_vals)

random_values : [0.38066619 0.9190777  0.98310004]


In [42]:
# Set seed for reproducibility
np.random.seed(0) # IT STOPS GENERATING RANDOM VALUES FOR EVERY EXECUTION
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("random_values :",random_vals)

random_values : [0.5488135  0.71518937 0.60276338]


In [43]:
# GENERATE RANDOM INTEGERS
rand_ints = np.random.randint(0,10,size =5)
print("Random Numbers:",rand_ints)

Random Numbers: [3 7 9 3 5]
